Bump toolchain/elemental-cli to 0.20220123
rancher-sandbox/cOS-toolkit pull request #1087
Opened 2022-01-23 17:45 UTC by cOS-cibot

Signed-off-by: cOS-cibot [bot] <cOScibot@gmail.com>

![JavaScript Arrays](./images/javascript-arrays.jpg)

2022-01-23 19:02 UTC, Itxaka requested changes

2022-01-23 19:02 UTC, Itxaka commented on packages/toolchain/elemental-cli/collection.yaml
> +      git.hash: "null"
Wat

2022-01-24 07:09 UTC, mudler commented on packages/toolchain/elemental-cli/collection.yaml
> +      git.hash: "null"
maybe  the repo rename ?

2022-01-24 08:50 UTC, Itxaka commented on packages/toolchain/elemental-cli/collection.yaml
> +      git.hash: "null"
```
$ curl https://api.github.com/repos/rancher-sandbox/elemental-cli/git/refs/heads/master
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/433378128/git/refs/heads/master",
  "documentation_url": "https://docs.github.com/v3/#http-redirects"
}
```

```
$ curl https://api.github.com/repositories/433378128/git/refs/heads/master
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest"
}

```

```
$ curl https://api.github.com/repos/rancher-sandbox/elemental/git/refs/heads/master            
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest"
}
```


:exploding_head:

2022-01-24 08:52 UTC, Itxaka commented on packages/toolchain/elemental-cli/collection.yaml
> +      git.hash: "null"
duh

its MAIN not MASTER ¬_¬

2022-01-24 08:54 UTC, closed without merging