Use grub2 in ISOs
rancher-sandbox/cOS-toolkit pull request #557
Opened 2021-08-27 11:09 UTC by davidcassany

This commit refactors grub2 usage in cOS. It adds a collection of
packages related to grub2 and configures ISOs generation to make
use of grub2 packages.

Fixes #521

Signed-off-by: David Cassany <dcassany@suse.com>

2021-08-30 06:13 UTC, mudler requested changes
Awesome! It looks good, but there is no bump to cOS, so tests  are hitting the hold grub configurations!

2021-08-30 07:01 UTC, davidcassany commented
> Awesome! It looks good, but there is no bump to cOS, so tests are hitting the hold grub configurations!

Ouch! you are right... 😓

2021-08-30 10:03 UTC, mudler approved these changes
Looks good here! let's just wait for CI to pass

2021-09-02 09:25 UTC, Itxaka commented on packages/grub2/build.yaml
> +{{if eq .Values.name "grub2-config"}}
very nice!

2021-09-02 09:26 UTC, Itxaka approved these changes

2021-09-02 09:27 UTC, mudler commented on make/Makefile.test
> +	VBoxManage storagectl "test" --name "sata controller" --add sata --portcount 2
One of the quirks of vbox I suppose :sweat_smile:

2021-09-02 19:37 UTC, merged