Default RPi serial console to 115200 bps
rancher-sandbox/cOS-toolkit pull request #990
Opened 2021-12-17 11:18 UTC by kkaempf

This is the [default baudrate](https://www.raspberrypi.com/documentation/computers/configuration.html#enabling-early-console-for-linux) on Raspberry Pi and also used by its bootloader.

Signed-off-by: Klaus Kämpf <kkaempf@suse.de>

2021-12-17 12:27 UTC, mudler requested changes
Thanks for the fixup! Although this PR as-is will change serial console args for all images, not only for the Pi

2021-12-17 12:34 UTC, mudler commented on examples/rpi/files/etc/cos/bootargs.cfg
> -    set kernelcmd="console=tty1 console=ttyS0 root=live:LABEL=$recoverylabel rd.live.dir=/ rd.live.squashimg=$img panic=5 modprobe.blacklist=vc4"
:+1:

2021-12-20 11:28 UTC, kkaempf commented
Hmm, if I only change `examples/rpi/files/etc/cos/bootargs.cfg` and rebuild the image, the new baudrate setting does _not_ show up in either `$(COS_RECOVERY)/etc/cos/bootargs.cfg` or `$(active.img)/etc/cos/bootargs.cfg`

2021-12-20 12:51 UTC, mudler commented
> Hmm, if I only change `examples/rpi/files/etc/cos/bootargs.cfg` and rebuild the image, the new baudrate setting does _not_ show up in either `$(COS_RECOVERY)/etc/cos/bootargs.cfg` or `$(active.img)/etc/cos/bootargs.cfg` 

How are you building the image? The script currently requires the image to be pushed, or either specify it's content with --directory

2021-12-21 09:47 UTC, mudler approved these changes

2021-12-21 09:47 UTC, mudler commented
CI is not going to run tests for this at the moment, going to merge it and test it manually

2021-12-21 09:47 UTC, merged